/* Table name: TRAVEL_REVIEW */
DROP TABLE TRAVEL_REVIEW;

CREATE TABLE TRAVEL_REVIEW(
    REVIEWNO       NUMBER(10)      NOT NULL,
    TRAVELNO    NUMBER(10)      NOT NULL, -- FK
    TITLE      VARCHAR2(50)      NOT NULL,   
    CONTENT    CLOB    NOT NULL,
    RECOM    NUMBER(7)    DEFAULT 0    NOT NULL,
    CNT    NUMBER(7)    DEFAULT 0   NOT NULL,
    RDATE    DATE    NOT NULL,
    FILE1    VARCHAR2(50)    NULL,
    FILE1_SAVED    VARCHAR2(50)    NULL,
    THUMB1    VARCHAR2(50)    NULL,
    MEMBERNO    NUMBER(10) NOT NULL, -- FK
    
    FOREIGN KEY (TRAVELNO) REFERENCES TRAVEL (TRAVELNO)
    FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
    PRIMARY KEY (REVIEWNO)
);

COMMENT ON TABLE TRAVEL_REVIEW is '여행지 리뷰';
COMMENT ON COLUMN TRAVEL_REVIEW.REVIEWNO is '여행지 리뷰 번호';
COMMENT ON COLUMN TRAVEL_REVIEW.TRAVELNO is '여행지 번호';
COMMENT ON COLUMN TRAVEL_REVIEW.TITLE is '제목';
COMMENT ON COLUMN TRAVEL_REVIEW.CONTENT is '내용';
COMMENT ON COLUMN TRAVEL_REVIEW.RECOM is '추천수';
COMMENT ON COLUMN TRAVEL_REVIEW.CNT is '조회수';
COMMENT ON COLUMN TRAVEL_REVIEW.RDATE is '등록일';
COMMENT ON COLUMN TRAVEL_REVIEW.FILE1 is '메인이미지';
COMMENT ON COLUMN TRAVEL_REVIEW.FILE1_SAVED is '실제 저장된 이미지';
COMMENT ON COLUMN TRAVEL_REVIEW.THUMB1 is '메인이미지 thumb';
COMMENT ON COLUMN TRAVEL_REVIEW.MEMBERNO is '회원번호';


DROP SEQUENCE TRAVEL_REVIEW_SEQ;

CREATE SEQUENCE TRAVEL_REVIEW_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 99999            -- 최대값: 99999 --> NUMBER(5) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지
